set shell       := ["bash", "-c"]
set dotenv-load := true
export APP_FQDN := env_var_or_default("APP_FQDN", "metaframe1.dev")
# Source of deno scripts. When developing we need to switch this
export DENO_SOURCE                 := env_var_or_default("DENO_SOURCE", "https://deno.land/x/metapages@v0.0.12")
bold            := '\033[1m'
normal          := '\033[0m'

@_help:
    just --list

# all one-off tasks to get started. idempotent
@init: mkcert

# DEV: generate TLS certs for HTTPS over localhost https://blog.filippo.io/mkcert-valid-https-certificates-for-localhost/
mkcert:
    deno run --allow-all --unstable {{DENO_SOURCE}}/commands/ensure_mkcert.ts --certs-dir=".certs"

clean:
    rm -rf .certs
    rm -rf conf.d/certs/*
