# Template docker-compose application

version: "2.4"

services:

  https:
    image: openresty/openresty:1.15.8.3-1-buster-fat-nosse42
    depends_on:
      server:
        condition: service_healthy
    environment:
      # point to both the application and the auth domain
      # they are separate because it makes auth logistically easier
      - "APP_FQDN=${APP_FQDN:-docker-run.dev}"
      - "APP_PORT=${APP_PORT:-443}"
    command: /start.sh
    volumes:
      - ./ingress/https/conf.d:/etc/nginx/conf.d
      - ./ingress/https:/app/https
      - ./ingress/https/start.sh:/start.sh
      - ./ingress/https/.certs:/etc/nginx/conf.d/certs
    networks:
      - default
    ports:
      # - ${PORT_SERVER:-8081}:8080
      - "${PORT_SERVER:-8080}:${APP_PORT:-443}"
    logging:
      driver: ${LOGGING_HTTPS:-none}

  server:
    command: just dev
    environment:
      # point to both the application and the auth domain
      # they are separate because it makes auth logistically easier
      - "BROWSER_ASSETS_DIRECTORY=/app/browser/dist/"
    volumes:
      - ./shared:/app/shared
      - ./browser/docs:/app/browser/dist
      - ./server/.cache:/app/server/.cache
      - ./server/src:/app/server/src
      - ./server/justfile:/app/server/justfile
      - ./server/package.json:/app/server/package.json
      - ./server/package-lock.json:/app/server/package-lock.json
      - ./server/tsconfig.json:/app/server/tsconfig.json
    # ports:
    #   - "${PORT_SERVER:-8081}:8080"

  worker:
    command: just dev --cpus=1 --queue=local1 --server=http://server:8080
    entrypoint: ''
    volumes:
      - ./shared:/app/shared
      - ./worker/.cache:/app/worker/.cache
      - ./worker/src:/app/worker/src
      - ./worker/justfile:/app/worker/justfile
      - ./worker/package.json:/app/worker/package.json
      - ./worker/package-lock.json:/app/worker/package-lock.json
      - ./worker/tsconfig.json:/app/worker/tsconfig.json


  # Contains browser files, can be published many different ways
  # Currently served via the service: api-public
  browser:
    depends_on:
      server:
        condition: service_healthy
    build:
      context: .
      dockerfile: browser/Dockerfile
      args:
        DOCKER_TAG: ${DOCKER_TAG:-local}
    command: just _dev
    environment:
      - APP_FQDN=${APP_FQDN:-metaframe1.dev}
      - APP_PORT=${APP_PORT:-443}
      - VITE_SERVER_ORIGIN=https://${APP_FQDN:-metaframe1.dev}:${PORT_SERVER:-8080}
    volumes:
      - ./package.json:/app/package.json
      - ./tsconfig.workspace.json:/app/tsconfig.workspace.json
      - ./shared:/app/shared
      - ./browser/dist:/app/browser/dist
      - ./browser/.cache:/app/browser/.cache
      - ./browser/public:/app/browser/public
      - ./browser/src:/app/browser/src
      - ./browser/justfile:/app/browser/justfile
      - ./browser/package.json:/app/browser/package.json
      - ./browser/package-lock.json:/app/browser/package-lock.json
      - ./browser/tsconfig.json:/app/browser/tsconfig.json
      - ./browser/vite.config.ts:/app/browser/vite.config.ts
      - ../.git:/.git
      - ./ingress/https/.certs:/app/ingress/https/.certs
    networks:
      - default
    ports:
      - "${APP_PORT:-443}:${APP_PORT:-443}"
