# Template docker-compose application
version: "2.4"
services:

  # Contains browser files, can be published many different ways
  # Currently served via the service: api-public
  browser-builder:
    x-publish: true
    image: ${DOCKER_REGISTRY:-}${DOCKER_IMAGE_PREFIX:-}browser-builder:${DOCKER_TAG:-cache}
    build:
      context: .
      dockerfile: browser/Dockerfile
      target: browser-builder
      cache_from:
        - ${DOCKER_REGISTRY:-}${DOCKER_IMAGE_PREFIX:-}browser-builder:cache

  # Contains browser files, can be published many different ways
  # Currently served via the service: api-public
  # browser:
  #   x-publish: true
  #   image: ${DOCKER_REGISTRY:-}${DOCKER_IMAGE_PREFIX:-}browser:${DOCKER_TAG:-cache}
  #   build:
  #     context: .
  #     dockerfile: browser/Dockerfile
  #     target: browser
  #     cache_from:
  #       - ${DOCKER_REGISTRY:-}${DOCKER_IMAGE_PREFIX:-}browser-builder:cache
  #       - ${DOCKER_REGISTRY:-}${DOCKER_IMAGE_PREFIX:-}browser:cache
