# just docs: https://github.com/casey/just
set shell       := ["bash", "-c"]
set dotenv-load := true
tsc             := "./node_modules/typescript/bin/tsc"
# minimal formatting, bold is very useful
bold            := '\033[1m'
normal          := '\033[0m'

@_help:
    just --list --unsorted

# Build the client static files
build: (_typescript "--build")

# compile typescript src, may or may not emit artifacts
_typescript +args="--build": _ensure_npm_modules
    {{tsc}} {{args}}

# rebuild the client on changes, but do not serve
watch:
    watchexec -w src -w tsconfig.json -w package.json -- just build

@_ensure_npm_modules:
    if [ ! -f "{{tsc}}" ]; then npm i; fi
