let origin = window.location.origin;
if (process.env.NODE_ENV === "development") {
    origin = `https://${process.env.APP_FQDN || "docker-run.dev"}${process.env.APP_PORT ? ":" + process.env.APP_PORT : ""
        }`;
    // currently read from .env.local generated by justfile
    if (process.env.APP_ORIGIN) {
        origin = process.env.APP_ORIGIN;
    }
    console.log(`NODE_ENV=== development => APP_ORIGIN=${origin}`)
}

export const APP_ORIGIN = origin;
